[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Change the board if you use another ESP32 module, for example:
; board = esp32dev
; board = esp32-c3-devkitm-1

; You can override flash wiring pins from here if desired:
; build_flags =
;   -D PIN_FLASH_CS=10
;   -D PIN_FLASH_SCK=12
;   -D PIN_FLASH_MISO=13
;   -D PIN_FLASH_MOSI=11
